services:
  - type: web
    name: student-success-grade
    env: docker
    plan: free
    branch: main # or master
    rootDir: . # root because Dockerfile is at repo root
    dockerfilePath: Dockerfile
    autoDeploy: true
